# Generated by Django 3.2.23 on 2023-11-07 05:06

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20231107_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Пoчтa'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
